version: "3.9"
services:

  app:
    build: .
    volumes:
      - .:/app
    ports:
      - 7000:7000
    command: python /app/manage.py runserver 0.0.0.0:7000
    env_file:
      - .env
    depends_on:
      - db

  db:
    image: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=postgres
