# Generated by Django 4.1.6 on 2023-02-11 07:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_rename_text_question_text2'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='text2',
            new_name='text',
        ),
    ]
