# Generated by Django 4.1.6 on 2023-02-11 07:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0003_rename_text2_question_text'),
    ]

    operations = [
        migrations.RenameField(
            model_name='choice',
            old_name='text',
            new_name='name',
        ),
    ]
