# Generated by Django 4.1.6 on 2023-02-11 07:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0004_rename_text_choice_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='choice',
            old_name='name',
            new_name='text',
        ),
    ]
